port: 7880
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 51000
  use_external_ip: false

redis:
  address: redis:6379
  password: "Jiqid@k10@2025"

turn:
  enabled: false
  # domain: yourdomain.com
  # tls_port: 5349
  # port: 3478
  # external_tls: true
  # external_port: 5349

keys:
  APIuyg8Hzi6QMVY: eOzFAqpaDjolBWshD9XXwXMFeCJF8nHAZeunNuoretbD


logging:
  json: false
  level: info

# 房间设置
room:
  empty_timeout: 60
  max_participants: 20