# 定义网络
networks:
  aosp_network:
    name: aosp_network
    driver: bridge

services:
  aosp-22001:
    image: aosp-build:latest
    container_name: aosp-22001
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    networks:
      - aosp_network
    ports:
      - "22001:22"
    volumes:
      - ${DATA_ROOT}/22001/aosp:/aosp  # 每个容器独立源码目录
      - ${DATA_ROOT}/22001/.ssh:/root/.ssh

  aosp-22002:
    image: aosp-build:latest
    container_name: aosp-22002
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    networks:
      - aosp_network
    ports:
      - "22002:22"
    volumes:
      - ${DATA_ROOT}/22002/aosp:/aosp  # 每个容器独立源码目录
      - ${DATA_ROOT}/22002/.ssh:/root/.ssh

  aosp-22003:
    image: aosp-build:latest
    container_name: aosp-22003
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    networks:
      - aosp_network
    ports:
      - "22003:22"
    volumes:
      - ${DATA_ROOT}/22003/aosp:/aosp  # 每个容器独立源码目录
      - ${DATA_ROOT}/22003/.ssh:/root/.ssh

  aosp-22004:
    image: aosp-build:latest
    container_name: aosp-22004
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    networks:
      - aosp_network
    ports:
      - "22004:22"
    volumes:
      - ${DATA_ROOT}/22004/aosp:/aosp  # 每个容器独立源码目录
      - ${DATA_ROOT}/22004/.ssh:/root/.ssh

  aosp-22005:
    image: aosp-build:latest
    container_name: aosp-22005
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    networks:
      - aosp_network
    ports:
      - "22005:22"
    volumes:
      - ${DATA_ROOT}/22005/aosp:/aosp  # 每个容器独立源码目录
      - ${DATA_ROOT}/22005/.ssh:/root/.ssh